---
- hosts: nodes
  become: yes
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Request NGINX index page from Jenkins Node
      tags: test
      uri:
        url: http://localhost
        return_content: yes
      register: nginx_index_response

    - name: Display NGINX index page content
      debug:
        var: nginx_index_response.content
      when: nginx_index_response.status == 200

    - name: Save NGINX index page to a file
      tags: save
      copy:
        content: "{{ nginx_index_response.content }}"
        dest: /tmp/nginx_index.html
