---
- hosts: nodes
  become: yes
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Request and save NGINX index page
      tags: save
      uri:
        url: http://localhost
        return_content: yes
      register: nginx_index_response

    - name: Save NGINX index page to a file
      tags: save
      copy:
        content: "{{ nginx_index_response.content }}"
        dest: /tmp/nginx_index.html
