---
- hosts: nodes
  become: yes
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Request NGINX index page
      tags: test
      uri:
        url: http://localhost
        return_content: yes
      register: nginx_index_response

    - name: Display NGINX index page content
      debug:
        var: nginx_index_response.content
      when: nginx_index_response.status == 200
